inputs:
  lookup:
    description: "User or organization name/Repository name"
    required: true
    type: string
  regexp:
    description: "Regular expression to remove extra characters from a tag name"
    required: false
    type: string

outputs:
  version:
    value: ${{ steps.release.outputs.version }}
    description: "The latest release version"
  description:
    value: ${{ steps.release.outputs.description }}
    description: "Short description of the release with a link to the original"

runs:
  using: composite
  steps:
    -
      name: Get latest release
      uses: actions/github-script@v7
      id: release
      env:
        INPUT_LOOKUP: ${{ inputs.lookup }}
        INPUT_REGEXP: ${{ inputs.regexp }}
      with:
        retries: 3
        script: |
          const regexp = core.getInput('regexp') || '/^v/gi';
          const [owner, repo] = core.getInput('lookup', { required: true }).split('/', 2);
          const { data } = await github.rest.repos.getLatestRelease({ owner, repo });

          const [_, pattern, flags] = regexp.split('/');
          core.setOutput(
              'version',
              data.tag_name.replace(new RegExp(pattern, flags), ''),
          );

          core.setOutput('description', `${data.body}\n${data.url}`);
