inputs:
  owner:
    required: true
    description: User or organization name
    type: string
  repo:
    required: true
    description: Repository name
    type: string
  regexp:
    required: false
    type: string
    default: '/^v/gi'
    description: Regular expression to remove extra characters from a tag name

outputs:
  version:
    value: ${{ steps.release.outputs.version }}
    description: The latest release version
  description:
    value: ${{ steps.release.outputs.description }}
    description: Short description of the release with a link to the original

runs:
  using: composite
  steps:
    -
      name: Get latest release
      uses: actions/github-script@v7
      id: release
      env:
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
        regexp: ${{ inputs.regexp }}
      with:
        retries: 3
        script: |
          const { owner, repo, regexp } = process.env;
          const { data } = await github.rest.repos.getLatestRelease({owner, repo});

          const [_, pattern, flags] = regexp.split('/');
          core.setOutput(
              'version',
              data.tag_name.replace(new RegExp(pattern, flags), ''),
          );

          core.setOutput('description', `${data.body}\n${data.url}`);
